### ISSUE TITLE
Problems when `K = 0` or `1` in `kmeans_init`

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/kmeans_R#34] opened 2018-03-16 01:30 UTC
If `K = 0` is given to `kmeans_init` then `kmeans_init` does not fail, but returns an empty matrix which causes `kmeans_cluster` to fail - and this failure is not graceful and has no error message. I would suggest changing this to an early and graceful fail in `kmeans_init` if `K = 0` is given.

```
> centers <- kmeans_init(data= synth_data, K = 0)
> centers
     [,1] [,2]
> kmeans_cluster(data = synth_data, centers = centers)
Error in centers[c, ] : subscript out of bounds
```

---
If `K = 1` is given to `kmeans_init` then a matrix of 3 rows is returned:
```
> kmeans_init(data= synth_data, K = 1)
          [,1]      [,2]
[1,]  2.736422  1.400745
[2,] 11.603569  6.200732
[3,]  7.482771 13.126711
```

And when this is passed to `kmeans_cluster` then 3 clusters are identified. I don't think this is the expected behaviour. If `K = 1` then wouldn't we expect only one cluster? Or at least a graceful failure/warning saying that `K` should be >= 2 if you don't think it makes sense to return only one cluster?

---
No problems were observed when `K` >= 2.

**Comment by ttimbers** [comment] 2018-03-16 01:38
Note - before you fix this in the code, I would recommend a writing a test that would catch these bugs and then fix your functions to address these bugs.

**Comment by johannesharmse** [comment] 2018-03-16 07:23
Thanks for the feedback.

These points can be seen as two separate issues, but will be addressed as one.

I agree that the case of `K = 0` can cause confusion. Even though this is not a bug, it does not integrate well with the rest of the package functions. The code has been changed so that the error message *"K value cannot be 0. Please specify the number of initial values as an integer larger than 0."* will be displayed if `K = 0` is given as input. New error handling tests are passing for this change. This change will be merged into the master branch once approved by the reviewers.

The case of `K = 1` was definitely a bug that slipped through. The code has been adjusted to return a matrix with one row if `K = 1` is given as input. A test has been added and is passing. I do believe that it is up to the user, whether they think `K = 1` is sensible, which is why allowing `K = 1` is probably better than giving an error message. This change will be merged into the master branch once approved by the reviewers.

**Comment by johannesharmse** [comment] 2018-03-17 06:32
Changes have successfully been implemented.

**Closed as completed by johannesharmse** 2018-03-17 06:32 UTC
